server:
  port: 8081

spring:
  application:
    name: bigproject
  datasource:
    url: jdbc:mysql://database-1.c1eg6m840npc.ap-southeast-2.rds.amazonaws.com:3306/guardrail?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: "Guardrail2026!"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3
  jpa:
    hibernate:
      ddl-auto: validate  
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true        
    properties:
      hibernate:
        format_sql: true  

jwt:
  issuer: ${JWT_ISSUER:bigproject}
  secret: ${JWT_SECRET:}
  access-token-expiration-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:3600}

github:
  token-encryption-key: "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI="
